# see https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features#git.asf.yamlfeatures-GitHubsettings

github:
  description: "Seamless multi-primary syncing database with an intuitive HTTP/JSON API, designed for reliability"
  homepage: https://couchdb.apache.org/
  labels:
    - database
    - content
    - network-server
    - http
    - cloud
    - erlang
    - javascript
    - couchdb
    - big-data
    - network-client
  features:
    issues: true
    projects: true
    discussions: true
  enabled_merge_buttons:
    squash: true
    rebase: true
    merge: true
  del_branch_on_merge: true
  protected_branches:
    main:
      required_status_checks:
        strict: true
        contexts:
          - continuous-integration/jenkins/pr-merge
      required_pull_request_reviews:
        # Set to true if you want to automatically dismiss approving reviews when someone pushes a new commit.
        dismiss_stale_reviews: false
        # Specifies the number of reviewers required to approve pull requests.
        # Use a number between 1 and 6 or 0 to not require reviewers.
        required_approving_review_count: 1
    fdbmain:
      required_status_checks:
        strict: true
        contexts:
          - continuous-integration/jenkins/pr-merge
    3.5.x:
      required_status_checks:
        strict: true
    3.4.x:
      required_status_checks:
        strict: true
    3.3.x:
      required_status_checks:
        strict: true
    3.2.x:
      required_status_checks:
        strict: true
    3.1.x:
      required_status_checks:
        strict: true
    3.0.x:
      required_status_checks:
        strict: true
    2.3.x:
      required_status_checks:
        strict: true
    2.1.x:
      required_status_checks:
        strict: true
    2.0.x:
      required_status_checks:
        strict: true
    1.6.x:
      required_status_checks:
        strict: true
    1.5.x:
      required_status_checks:
        strict: true
    1.4.x:
      required_status_checks:
        strict: true
    1.3.x:
      required_status_checks:
        strict: true
    1.x.x:
      required_status_checks:
        strict: true

notifications:
  commits: commits@couchdb.apache.org
  issues: notifications@couchdb.apache.org
  pullrequests: notifications@couchdb.apache.org
  discussions: notifications@couchdb.apache.org
  # This would send new/closed PR notifications to dev@
  #pullrequests_status: dev@couchdb.apache.org
  # This would send individual PR comments/reviews to notifications@
  #pullrequests_comment: notifications@couchdb.apache.org
