name: Bug report
description: Describe a scenario in which CouchDB behaves unexpectedly
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - unknown
        - 3.0.0
        - 3.0.1
        - 3.1.0
        - 3.1.1
        - 3.1.2
        - 3.2.0
        - 3.2.1
        - 3.2.2
        - 3.2.3
        - 3.3.0
        - 3.3.1
        - 3.3.2
        - 3.3.3
        - 3.4.0
        - 3.4.1
        - 3.4.2
        - 3.4.3
        - 3.5.0
        - 3.5.1
      default: 0
  - type: textarea
    id: summary
    attributes:
      label: Describe the problem you're encountering
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description:  Tell us what you expected to happen
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: Include commands to reproduce, if possible. curl is preferred
  - type: textarea
    id: environment
    attributes:
      label: Your Environment
      description: Include as many relevant details about your environment as possible
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
