#!/bin/sh -e

# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

# This script is called by the build system and is used to provide an error
# about missing or empty files. Some files are optional, and will be built when
# the environment allows. But these files are required for distribution.

cat << EOF
ERROR: This file is missing or incomplete:

       $1

       This file is optional at build and install time,
       but is required when preparing a distribution.
EOF

exit 1
