#!/bin/sh -e

# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

# This script is called by the build system and is used to touch the list of
# expected output files when sphinx-build is not available. If the files exist,
# this will satisfy make. If they do not exist, we create of empty files.

if test -z "`which sphinx-build`"; then
    for file in $*; do
        mkdir -p `dirname $file`
        touch $file
    done
fi