ExUnit.configure(formatters: [JUnitFormatter, ExUnit.CLIFormatter])
:application.set_env(:kernel, :error_logger, false)
:application.load(:sasl)
:application.set_env(:sasl, :sasl_error_logger, false)
ExUnit.start()
