services:
  couch:
    # Select a pre-built image hosted on GHCR
    # image: ghcr.io/apache/couchdb:devcontainer-erlang-24-fdb-6.3.23

    # Alternatively, build your own image on-demand
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # The Erlang version determines our base image, which means it
        # implicitly selects versions for ICU + SpiderMonkey as well.
        ERLANG_VSN: "24"

        # This selects the FoundationDB client version. Typically you'd
        # want it to match the server version in fdb.image below.
        FDB_VSN: "6.3.23"

        # The Fauxton UI has a Node.js build-time dependency, most of
        # the time there's no reason to change this.
        NODE_VSN: "14"

    environment:
      # This needs to match the name of the FoundationDB service below
      FDB_COORDINATOR: fdb

      # The location where the FDB cluster file is created on container
      # startup. CouchDB looks for the cluster file in this location by
      # default. If you want to install it somewhere else you need to
      # change "[erlfdb] cluster_file" and ERL_ZFLAGS to match.
      FDB_CLUSTER_FILE: /usr/local/etc/foundationdb/fdb.cluster

      # The test suite will default to trying to start its own fdbserver
      # process. This environment variable tells it to use the fdbserver
      # running in the `fdb` image instead. Quite a hacky solution. An
      # alternative might be to parameterize the Makefile so we can swap
      # `eunit.config` for a `devcontainer.config` via an environment variable
      # and maintain both config files in the repo.
      ERL_ZFLAGS: "-erlfdb test_cluster_file <<\\\"/usr/local/etc/foundationdb/fdb.cluster\\\">>"

    volumes:
      # Mounts the project folder to '/usr/src/couchdb'. The target path inside
      # the container should match what your application expects. In this case,
      # the compose file is in a sub-folder, so you will mount '..'. You would
      # then reference this path as the 'workspaceFolder' in
      # '.devcontainer/devcontainer.json' so VS Code starts here.
      - ..:/usr/src/couchdb:cached

    network_mode: service:fdb

  fdb:
    # This is the version of the FDB server that will run alongside CouchDB
    image: foundationdb/foundationdb:6.3.23
