#!/bin/sh

export HOME=
export ERL_FLAGS="-couch_ini ${SNAP}/couchdb/etc/default.ini ${SNAP}/couchdb/etc/snap.ini ${SNAP_DATA}/local.ini"
if [ ! -e ${SNAP_DATA}/local.ini ]; then
    touch ${SNAP_DATA}/local.ini
fi

exec ${SNAP}/couchdb/bin/couchdb
