{application, mochiweb,
 [{description, "MochiMedia Web Server"},
  {vsn, "0.01"},
  {modules, [
        mochihex,
        mochijson,
        mochijson2,
        mochinum,
        mochiweb,
        mochiweb_app,
        mochiweb_charref,
        mochiweb_cookies,
        mochiweb_echo,
        mochiweb_headers,
        mochiweb_html,
        mochiweb_http,
        mochiweb_multipart,
        mochiweb_request,
        mochiweb_response,
        mochiweb_skel,
        mochiweb_socket_server,
        mochiweb_sup,
        mochiweb_util,
        reloader,
        mochifmt,
        mochifmt_std,
        mochifmt_records
	    ]},
  {registered, []},
  {mod, {mochiweb_app, []}},
  {env, []},
  {applications, [kernel, stdlib]}]}.
