name: Run Gradle on PRs
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        java: [ '11', '20' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - name: Run Gradle Builds
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: nouveau
